version: '3.8'
services:
  site-dev:
    image: ghcr.io/sladesouzasantos/website-portfolio:latest
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "8082:80"
    networks:
      - phass-network

networks:
  phass-network:
    external: true